import 'package:rent_home/models/year.dart';
import 'month_details.dart';

//!THIS CLASS IS USED FOR SHOWING PIE CHART
class DummyRenter {
  String name, flatNo;
  int floor, id;
  bool isPaid, isNotified;
  List<Year>? records;
  DummyRenter(
      {required this.id,
      required this.name,
      required this.floor,
      this.flatNo = '',
      required this.isPaid,
      this.isNotified = false,
      this.records});
}

List<DummyRenter> dummyRenters = [
  DummyRenter(
    id: 0,
    name: 'Ashraful Alam',
    floor: 2,
    isNotified: true,
    isPaid: false,
    records: [
      Year(
        yearNo: 2022,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2021,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2020,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
    ],
  ),
  DummyRenter(
    //lived two years
    id: 1,
    name: 'Motiur Rahman',
    floor: 2,
    isNotified: false,
    isPaid: false,
    records: [
      Year(
        yearNo: 2022,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2021,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
    ],
  ),
  DummyRenter(
    //lived five years
    id: 3,
    name: 'Rabiul Alam',
    floor: 2,
    flatNo: 'B',
    isPaid: true,
    records: [
      Year(
        yearNo: 2022,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2021,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2019,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2018,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2017,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
    ],
  ),
  DummyRenter(
    //living for a yeaer
    id: 4,
    name: 'Monirul  Hoque',
    floor: 3,
    flatNo: 'C',
    isPaid: false,
    isNotified: false,
    records: [
      Year(
        yearNo: 2022,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          // MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          // MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          // MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          // MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          // MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          // MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
    ],
  ),
  DummyRenter(
    id: 5,
    name: 'Jinia Islam',
    floor: 3,
    flatNo: '3A',
    isPaid: true,
    records: [
      Year(
        yearNo: 2022,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2021,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2020,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
    ],
  ),
  DummyRenter(
    id: 6, //living for two years
    name: 'Rubayat Hossain',
    floor: 4,
    isNotified: true,
    isPaid: false,
    records: [
      Year(
        yearNo: 2022,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
      Year(
        yearNo: 2021,
        months: [
          MonthDetails(monthNmae: 'Jan', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Feb', noOfDays: "28", paidAt: 5),
          MonthDetails(monthNmae: 'Mar', noOfDays: "31", paidAt: 2),
          MonthDetails(monthNmae: 'Apr', noOfDays: "30", paidAt: 6),
          MonthDetails(monthNmae: 'May', noOfDays: "31", paidAt: 15),
          MonthDetails(monthNmae: 'Jun', noOfDays: "30", paidAt: 31),
          MonthDetails(monthNmae: 'Jul', noOfDays: "31", paidAt: 8),
          MonthDetails(monthNmae: 'Aug', noOfDays: "30", paidAt: 15),
          MonthDetails(monthNmae: 'Sep', noOfDays: "31", paidAt: 3),
          MonthDetails(monthNmae: 'Oct', noOfDays: "30", paidAt: 30),
          MonthDetails(monthNmae: 'Nov', noOfDays: "31", paidAt: 12),
          MonthDetails(monthNmae: 'Dec', noOfDays: "30", paidAt: 16),
        ],
      ),
    ],
  ),
];
