// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYEiUKqHQ4aGxUAljsF8VrGCX9Ya2mEg4',
    appId: '1:121043908992:web:3a8e780ff48569f66fa965',
    messagingSenderId: '121043908992',
    projectId: 'sweet-home-18566',
    authDomain: 'sweet-home-18566.firebaseapp.com',
    storageBucket: 'sweet-home-18566.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1eLdbaXJ8kj9TAEyOF67GlamPDSJwwhA',
    appId: '1:121043908992:android:5b4d0084fda7bd826fa965',
    messagingSenderId: '121043908992',
    projectId: 'sweet-home-18566',
    storageBucket: 'sweet-home-18566.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsckvUbVJcJrtYqoullsWmLhk-R34gV74',
    appId: '1:121043908992:ios:9723f644fc28964b6fa965',
    messagingSenderId: '121043908992',
    projectId: 'sweet-home-18566',
    storageBucket: 'sweet-home-18566.appspot.com',
    iosClientId: '121043908992-uiu1o1k03uno0ir7cjboilfuck0uaqtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentHome',
  );
}
